### ISSUE TITLE
Add LFmap source file?

### ISSUE THREAD

**Issue by MaxNeksueb** [F-Tomas/pylfmap#1]
@F-Tomas Hi Tomas, I think it would be useful to add the source file of LFmap to the repository to have it archived. People in the field still often use it but it's only available on the original website, which is pretty old by now and could be taken offline anytime. 
What do you think? One could also archive it in a separate repository, if you want to keep this repo cleaner/smaller.

**Comment by F-Tomas** [comment]
Hi Max, I agree and that is something that I was also thinking to do. But I guess that for this I would need approval from the original author.

**Comment by kewenz** [comment]
Hello Tomas, I have same issue with the source file of LFmap, is it no longer an open source?

**Comment by F-Tomas** [comment]
@MaxNeksueb  @kewenz Hi, I wrote to Emil Polisensky (author of the LFmap) about this and he migrated the LFmap to the github, check [here](https://github.com/epolisensky/LFmap). I have also update the pylfmap and made a new release 0.3.1 also at pip.
